%%% This file was automatically generated by snmpc_mib_to_hrl version 4.24.2
%%% Date: 24-Dec-2013::16:34:21
-ifndef('COWBOY-MIB').
-define('COWBOY-MIB', true).

%% Oids

-define(otpModule, [1,3,6,1,4,1,193,19,1,1,100]).

-define(cowboyMIB, [1,3,6,1,4,1,193,19,3,100]).

-define(cowboyMIBConformance, [1,3,6,1,4,1,193,19,3,100,1]).

-define(cowboyMIBCompliances, [1,3,6,1,4,1,193,19,3,100,1,1]).

-define(cowboyMIBGroups, [1,3,6,1,4,1,193,19,3,100,1,2]).

-define(cowboyGroup, [1,3,6,1,4,1,193,19,3,100,1,2,1]).

-define(cowboyMIBObjects, [1,3,6,1,4,1,193,19,3,100,2]).
-define(cowboyTotalRequests, [1,3,6,1,4,1,193,19,3,100,2,1]).
-define(cowboyTotalRequests_instance, [1,3,6,1,4,1,193,19,3,100,2,1,0]).


%% Range values
-define(low_cowboyTotalRequests, 0).
-define(high_cowboyTotalRequests, 4294967295).


%% Default values
-define(default_cowboyTotalRequests, 0).

-endif.
