%%% This file was automatically generated by snmpc_mib_to_hrl version 4.25
%%% Date: 04-Jan-2014::17:07:02
-ifndef('COWBOY-MIB').
-define('COWBOY-MIB', true).

%% Oids

-define(otpModule, [1,3,6,1,4,1,193,19,1,1,100]).

-define(cowboyMIB, [1,3,6,1,4,1,193,19,3,100]).

-define(cowboyMIBConformance, [1,3,6,1,4,1,193,19,3,100,1]).

-define(cowboyMIBCompliances, [1,3,6,1,4,1,193,19,3,100,1,1]).

-define(cowboyMIBGroups, [1,3,6,1,4,1,193,19,3,100,1,2]).

-define(cowboyRequestGroup, [1,3,6,1,4,1,193,19,3,100,1,2,1]).

-define(cowboyResponseGroup, [1,3,6,1,4,1,193,19,3,100,1,2,2]).

-define(cowboyMIBObjects, [1,3,6,1,4,1,193,19,3,100,2]).

-define(request, [1,3,6,1,4,1,193,19,3,100,2,1]).
-define(totalRequests, [1,3,6,1,4,1,193,19,3,100,2,1,1]).
-define(totalRequests_instance, [1,3,6,1,4,1,193,19,3,100,2,1,1,0]).

-define(requestTable, [1,3,6,1,4,1,193,19,3,100,2,1,2]).

-define(requestEntry, [1,3,6,1,4,1,193,19,3,100,2,1,2,1]).
-define(requestMethod, 1).
-define(requestMethodCount, 2).

-define(response, [1,3,6,1,4,1,193,19,3,100,2,2]).
-define(totalResponses, [1,3,6,1,4,1,193,19,3,100,2,2,1]).
-define(totalResponses_instance, [1,3,6,1,4,1,193,19,3,100,2,2,1,0]).
-define(totalResponseSize, [1,3,6,1,4,1,193,19,3,100,2,2,2]).
-define(totalResponseSize_instance, [1,3,6,1,4,1,193,19,3,100,2,2,2,0]).

-define(responseTable, [1,3,6,1,4,1,193,19,3,100,2,2,3]).

-define(responseEntry, [1,3,6,1,4,1,193,19,3,100,2,2,3,1]).
-define(responseCode, 1).
-define(responseCodeCount, 2).
-define(responseCodeSize, 3).


%% Range values
-define(low_totalRequests, 0).
-define(high_totalRequests, 4294967295).
-define(low_requestMethod, 0).
-define(high_requestMethod, 255).
-define(low_requestMethodCount, 0).
-define(high_requestMethodCount, 4294967295).
-define(low_totalResponses, 0).
-define(high_totalResponses, 4294967295).
-define(low_totalResponseSize, 0).
-define(high_totalResponseSize, 4294967295).
-define(low_responseCode, 0).
-define(high_responseCode, 255).
-define(low_responseCodeCount, 0).
-define(high_responseCodeCount, 4294967295).
-define(low_responseCodeSize, 0).
-define(high_responseCodeSize, 4294967295).


%% Default values
-define(default_totalRequests, 0).
-define(default_requestMethodCount, 0).
-define(default_totalResponses, 0).
-define(default_totalResponseSize, 0).

-endif.
